---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: Remove Trailing Whitespaces
      - id: end-of-file-fixer
        name: Fix End-Of-File Endings
      - id: check-yaml
        name: Check YAML
      - id: check-added-large-files
        name: Check For Large Files
      - id: detect-private-key
        name: Detect Private Keys
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.20
    hooks:
      - id: tflint
        args:
          - "--module"
          - "--config=.tflint.hcl"
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.2
    hooks:
      - id: terraform_fmt
        name: Terraform FMT
      - id: terragrunt_fmt
        name: Terragrunt FMT
      - id: terraform_tfsec
        name: Terraform Security
        exclude: .terragrunt-cache
      - id: terraform_docs
        name: Terraform Docs
      - id: tfupdate
        name: Autoupdate Terraform Versions
      - id: terrascan
        name: Terrascan
        args:
          - --args=--non-recursive # avoids scan errors on subdirectories without Terraform config files
          - --args=--policy-type=azure
      - id: checkov
        args:
          - "--skip-check=CKV_AWS_39,CKV_AWS_18"
        name: Checkov
      - id: terraform_tfsec
        name: TF Security
